language: scala
scala:
  - 2.10.4
  - 2.11.7
jdk:
  - oraclejdk7
  - oraclejdk8
matrix:
  include:
  - scala: 2.12.0-RC1
    jdk: oraclejdk8
services:
  - postgresql
  - mysql
cache:
  directories:
    - vendor/bundle
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt
before_script:
  - ./script/prepare_build.sh

notifications:
  email:
    - linhares.mauricio@gmail.com
